Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace ContactManagement.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome do contato")]
        [MinLength(5, ErrorMessage = "Nome deve ter no mínimo 5 caracteres")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Digite o email do contato")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é válido!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Digite o número do contato")]
        [Phone(ErrorMessage = "O número informado não é válido")]
        [MaxLength(9)]
        public string Contato { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace ContactManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContatoController.cs
using ContactManagement.Models;
using ContactManagement.Repositório;
using Microsoft.AspNetCore.Mvc;

namespace ContactManagement.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio =  contatoRepositorio;
        }
        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListarPorId(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MenssagemSucesso"] = "Contato excluído com sucesso";
                }
                else
                {
                    TempData["MenssagemErro"] = "Não foi possível excluir";
                }
                
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                TempData["MenssagemErro"] = $"Não foi possível excluir: {e.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Adicionar(contact);
                    TempData["MenssagemSucesso"] = "Contato cadastrado com sucesso";
                    return RedirectToAction("Index");
                }

                return View(contact);
            }
            catch(Exception e)
            {
                TempData["MenssagemErro"] = $"Não foi possível cadastrar: {e.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _contatoRepositorio.Atualizar(contact);
                    TempData["MenssagemSucesso"] = "Contato alterado com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", contact);
            }
            catch(Exception e)
            {
                TempData["MenssagemErro"] = $"Não foi possível alterar: {e.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/HomeController.cs
using ContactManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ContactManagement.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação apagar o contato";
}

<div class="text-center">
    <br/>
    <h3>Deseja apagar realmente o contato (@Model.Nome)?</h3>
    <br/>
    <a class="btn btn-primary btn-block" role="button" asp-controller="Contato" asp-action="Index">Cancelar exclusão</a>
    <a class="btn btn-primary btn-danger" role="button" asp-route-id="@Model.Id" asp-controller="Contato" asp-action="Apagar">Confirmar exclusão</a>
</div>

Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Cadastrar Contatos";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar Contatos</h1>
</div>
    <form asp-controller="Contato" asp-action="Criar" method="post">
      <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
        @Html.ValidationMessageFor(x => x.Nome)
      </div>

      <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
        @Html.ValidationMessageFor(x => x.Email)
      </div>

      <div class="form-group">
        <label for="contato">Contato</label>
        <input type="text" asp-for="Contato" class="form-control" placeholder="Digite o número do contato">
        @Html.ValidationMessageFor(x => x.Contato)
      </div>
      <br/>
      <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
      <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
    </form>

Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar Contato";
}

<div class="text-center">
    <h1 class="display-4">Editar Contato</h1>
</div>

    <form asp-controller="Contato" asp-action="Alterar" method="post">

        <input type="hidden" asp-for="Id" />
        
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do contato">
            @Html.ValidationMessageFor(x => x.Nome)
        </div>

        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do contato">
            @Html.ValidationMessageFor(x => x.Email)
        </div>

        <div class="form-group">
            <label for="contato">Contato</label>
            <input type="text" asp-for="Contato" class="form-control" placeholder="Digite o número do contato">
            @Html.ValidationMessageFor(x => x.Contato)
        </div>
        <br/>
        <button type="submit" class="btn btn-primary btn-block">Alterar</button>
        <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>

    </form>

Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo contato</a>
    </div>
    <br/>
    @if(TempData["MenssagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MenssagemSucesso"]
        </div>
    }

    @if(TempData["MenssagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MenssagemErro"]
        </div>
    }
    <br/>

    <h1 class="display-4">Listagem de Contatos</h1>
    <p></p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">E-mail</th>
          <th scope="col">Contato</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
            @if(Model != null && Model.Any())
            {
                foreach(ContatoModel contato in Model)
                {
                    <tr>
                      <th scope="row">@contato.Id</th>
                      <td>@contato.Nome</td>
                      <td>@contato.Email</td>
                      <td>@contato.Contato</td>
                      <td>
                          <div class="btn-group" role="group" aria-label="Basic example">
                            <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="ApagarConfirmacao">Apagar</a>
                        </div>
                      </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Contact Management</h1>
    <br/>
    <p>Sistema de Controle de Contatos</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Gerenciar Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ContactManagement
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>